### ISSUE TITLE
List breaking data model changes in eos_cli_config_gen in release notes

### ISSUE THREAD

**Issue by melkypie** [aristanetworks/ansible-avd#1730]
### Enhancement summary

It would be great if any breaking data model changes that happen in eos_cli_config_gen could be listed in release notes. Since we now have the ability to set custom structured configuration that allows us to interact with eos_cli_config_gen directly and due to Jinja2 being really unhelpful with the errors it provides when a data model change happens.

### Which component of AVD is impacted

others

### Use case example

Currently the only way I know of sending syslog out of an Arista is using a custom structured configuration as I can't find a eos_designs model for it. So I have this which worked perfectly fine before 3.4.0 and before 01e4f11a3c0faf905451f561242921fe9a1e8cd1.
```yaml
csc_logging:
  monitor: informational
  buffered:
    size: 525000
    level: informational
  vrfs:
    OOB:
      source_interface: Management1
      hosts:
        - 10.0.0.1
```
After 01e4f11a3c0faf905451f561242921fe9a1e8cd1 it turns into this:
```yaml
csc_logging:
  monitor: informational
  buffered:
    size: 525000
    level: informational
  vrfs:
    - name: OOB
      source_interface: Management1
      hosts:
        - name: 10.0.0.1
```
which is not backwards compatible with pre 01e4f11a3c0faf905451f561242921fe9a1e8cd1 version. So Jinja2 throws me a really unhelpful error (`{"changed": false, "msg": "AnsibleUndefinedVariable: 'ansible.parsing.yaml.objects.AnsibleUnicode object' has no attribute 'name'"}`) that took me a couple of hours to figure out by running a molecule while doing git bisect. So it would be really helpful to know what breaking data model changes happen in `eos_cli_config_gen` the same way they are announced when they happen in `eos_designs`.

### Describe the solution you would like

Similar to how breaking changes are announced for eos_designs when releasing a major version.

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct

**Comment by ClausHolbechArista** [comment]
We have not changed the data model (on purpose at least). In this case we are interpreting the data model a bit stricter than it was before, but the documentation still says:
```
logging:
  ...
  vrfs:
    < vrf_name >:
      source_interface: < source_interface_name >
      hosts:
        < syslog_server_1 >:
          protocol: < tcp | udp (default udp) >
          ports:
            - < custom_port_1 >
            - < custom_port_2 >
```
So `hosts` is a dictionary, and not a list like you had in your original data.
We found a similar conflict in our molecule tests, so we updated that. Maybe your original data was inspired by that (incorrect) example? If not, please help identify the source of the incorrect model.
We are preparing for future conversion to lists, so we currently accept both dictionaries and lists of dictionaries - but not a flat list like you had.
So your updated model will also work for AVD 4.0.
Thanks

**Comment by ClausHolbechArista** [comment]
I just checked, and the change from list -> dict was part of AVD 3.0.0. And this change was in fact listed as a data model change in the release-notes for 3.0.0.

```
#Old data model
logging:
  vrfs:
    < vrf_name >:
      source_interface: < source_interface_name >
      hosts:
        - < syslog_server_1>
        - < syslog_server_2>

# New data model
logging:
  vrfs:
    < vrf_name >:
      source_interface: < source_interface_name >
      hosts:
        < syslog_server_1 >:
          protocol: < tcp | udp (default udp) >
          ports:
            < custom_port_1 >
            < custom_port_2 >
        < syslog_server_2 >:
          ports:
            < custom_port_1 >
```

**Comment by melkypie** [comment]
Seems to have been my fault for not reading through the release notes fully, it just seemed weird to me that it broke on 3.4.0 while it worked fine through 3.0.0 until 3.4.0 when it finally broke, so that is why I was confused.
