### ISSUE TITLE
In case of pure L2VNI mode, eos_cli_config_gen fails to generate VXLAN interface

### ISSUE THREAD

**Issue by titom73** [aristanetworks/ansible-avd#78]
## Summary:

In case only you defined only L2 VNIs in your tenants, CLI config gen fails with follfowing elements:

```
FAILED! => changed=false 
  msg: 'AnsibleUndefinedVariable: ''dict object'' has no attribute ''vrfs'''
```

## Context information:

- `arista.avd` version 1.0.0
- ansible 2.9
- Impacted file: [vxlan-interface.j2](https://github.com/aristanetworks/ansible-avd/blob/master/ansible_collections/arista/avd/roles/eos_cli_config_gen/templates/eos/vxlan-interface.j2)

## Solution:

```jinja
{% if vxlan_tunnel_interface.Vxlan1.vxlan_vni_mappings.vrfs is defined and 
vxlan_tunnel_interface.Vxlan1.vxlan_vni_mappings.vrfs is not none %}
{%     for vrf in vxlan_tunnel_interface.Vxlan1.vxlan_vni_mappings.vrfs | arista.avd.natural_sort %}
   vxlan vrf {{ vrf }} vni {{ vxlan_tunnel_interface.Vxlan1.vxlan_vni_mappings.vrfs[vrf].vni }}
{%     endfor %}
{% endif %}
```

Instead of:

```jinja
{%     for vrf in vxlan_tunnel_interface.Vxlan1.vxlan_vni_mappings.vrfs | arista.avd.natural_sort %}
   vxlan vrf {{ vrf }} vni {{ vxlan_tunnel_interface.Vxlan1.vxlan_vni_mappings.vrfs[vrf].vni }}
{%     endfor %}
```

Same change should been done in documentation part of the role.

## Notes

Abstraction role (`eos_l3ls_config`) has not been tested as we are using a custom role to generate VXLAN HER topology.

**Comment by titom73** [comment]
Pull Request will come later after additional tests and ensure documentation is also compatible.

**Comment by carlbuchmann** [comment]
@titom73 since eos_cli_config_gen is also meant to work independently from eos_l3ls_evpn role we should also review the other templates, and ensure we test if the key is defined and not none!

**Comment by adirir** [comment]
HI
I'm trying to set AVD demo 2 spines and 4 leafs, I follow instructions on repo posted by Titom, playbook runs but complaining
ansible.errors.AnsibleUndefinedVariable: 'overlay_loopback_network_summary' is undefined
where is variable is defined? t

**Comment by adirir** [comment]
here is the jinja2 file..
{# Set Spine Variables #}
{% set switch.platform = spine.platform %}
{% set switch.mgmt_ip = spine.nodes[inventory_hostname].mgmt_ip %}
{% set switch.spanning_tree_mode = "none" %}
{% if bgp_as is arista.avd.defined and switch.overlay_routing_protocol == 'ibgp' %}
{%     set switch.bgp_as = bgp_as %}
{% else %}
{%     set switch.bgp_as = spine.bgp_as | arista.avd.default() %}
{% endif %}
{% set switch.router_id = overlay_loopback_network_summary | ipaddr('network') | ipmath(spine.nodes[inventory_hostname].id) %}
{% set switch.bgp_defaults = spine_bgp_defaults | arista.avd.default([]) %}
{# Logic for EVPN Role for Overlay BGP Peerings #}
{# For spine the default value is server #}
{% set switch.evpn_role = spine.nodes[inventory_hostname].evpn_role | arista.avd.default(
                          'server') %}
{% set switch.raw_evpn_route_servers = spine.nodes[inventory_hostname].evpn_route_servers | arista.avd.default(
                                       []) %}
